### ISSUE TITLE
Embed Tweets

### ISSUE THREAD

**Issue by vvidday** [vvidday/orbital-frontend#12]
- Utilize [react-twitter-embed](https://www.npmjs.com/package/react-twitter-embed) to embed tweets
- Sanitize links & miscellaneous
  - t.co -> Show image
  - Get rid of misc text such as `\n`

**Comment by guowei42** [comment]
Commit [b13f2c6](https://github.com/vvidday/orbital-frontend/commit/b13f2c61e185538948529528dc777165fe12f8f2), [4cc4b40](https://github.com/vvidday/orbital-frontend/commit/4cc4b4081dd0992aed28548021be2e7b28dbe040)

Added Tweet Embed Package
Twitter embed changes on selecting answer.

**Comment by vvidday** [comment]
### Image / Video display
Commit 2540c1fa935946e7692ee1c2692c4602536ecec1:
- Added support for new get tweet function that gets additional details of tweet from API, including image URLs and video preview URLs

Commit 5d7a24eeea11e7aea0f4069900aff8ed1b730677:
- Modified existing files (`buffer.js` and `gameImproved.js`) to work with new tweet object obtained from above
- Previously, data object was in format
```

{
	account: {accountObj},
	post: string
	id: string
	choices: []
}

```
- Now, `id` was removed and `post` is changed into an object containing `media`, an array of URLs:
```
{
	account: {accountObj},
	post: {
		id: string
		text: string
		media: string[]
	      }
	choices: []
}
```

Commit efefc3f2f4964457756baefabf779cc152354ca2:

- Tweaked `mainDisplay` to display images from new `post` object
- Added a basic custom "slider" to move between images
