### ISSUE TITLE
Cleaning Up

### ISSUE THREAD

**Issue by vvidday** [vvidday/orbital-frontend#16]
- Refactor long code in game and other "big" components into smaller components / files
- Change global variables to state.
   - Buffer data
   - Score

**Comment by guowei42** [comment]
Commit [65f3022](https://github.com/vvidday/orbital-frontend/commit/65f3022c4ef5ca165523e777ac06e4b12690b3c9)

Moved main display, which includes guessing post and twitter embed to its own file.

**Comment by vvidday** [comment]
Commit f789840d1b580f3e1514344433f301db282dca21

Handled merge conflicts between branches `twitter-embed` and `twitter-auth`. Mainly:

- Merged new features for buttons - dynamic CSS/styling from `twitter-embed` and game state changes from `twitter-auth`.
- Cleaned up imports/renaming for certain files
- Cleaned up states in parent file `App.js`
See more #18
